<?php

namespace App\Filament\Resources\AssetResource\RelationManagers;

use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class DepreciationsRelationManager extends RelationManager
{
    protected static string $relationship = 'depreciations';

    public function canCreate(): bool
    {
        // Depreciations are generated by service; keep read-only here to avoid accidental posting
        return false;
    }

    public function form(Form $form): Form
    {
        return $form; // read-only
    }

    public function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('period_start')->date()->label('Start')->sortable(),
                TextColumn::make('period_end')->date()->label('End')->sortable(),
                TextColumn::make('amount')->money('ngn', true)->sortable(),
                Tables\Columns\BadgeColumn::make('status')
                    ->colors([
                        'secondary' => 'pending',
                        'success' => 'posted',
                    ])->sortable(),
                TextColumn::make('posted_at')->dateTime()->toggleable(),
                TextColumn::make('ledger_journal_id')->label('Journal #')->toggleable(),
            ])
            ->headerActions([])
            ->actions([])
            ->bulkActions([]);
    }
}
